version: "3.0"

services:
    financial.api:
        hostname: financial-api
        container_name: financial-api
        networks:
           - financial-net
        restart: always
        build:
            context: .
            dockerfile: ../src/Encinecarlos.FinancialManager.Api/Dockerfile
        ports:
            - 9020:80
            - 9023:443
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 0.5GB
                reservations:
                    cpus: "0.25"
                    memory: 500M
networks:
    financial-net:
        driver: bridge